# Generated by Django 3.1.3 on 2020-11-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_post_unlikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='unlikes',
            new_name='dislikes',
        ),
    ]
