# Generated by Django 3.1.3 on 2020-11-22 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0011_auto_20201122_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
    ]
