# Generated by Django 3.1.3 on 2020-11-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0013_auto_20201126_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Snippet to be Added', max_length=200),
        ),
    ]
